<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Shubh_51" failures="1" tests="1" name="Test(failed)(failed)" time="38.92" errors="0" timestamp="2024-08-25T14:52:25 IST">
  <testcase classname="com.comcast.crm.testngassert.contacttest.ContactTest" name="createContactWithOrganizationTest" time="29.363">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [HDFC_357] but found [ HDFC_357]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [HDFC_357] but found [ HDFC_357]
at com.comcast.crm.testngassert.contacttest.ContactTest.createContactWithOrganizationTest(ContactTest.java:123)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createContactWithOrganizationTest -->
  <testcase classname="com.comcast.crm.testngassert.contacttest.ContactTest" name="createContactWithSupportDateTest" time="0.0">
    <ignored/>
  </testcase> <!-- createContactWithSupportDateTest -->
  <testcase classname="com.comcast.crm.testngassert.contacttest.ContactTest" name="createContactTest" time="0.0">
    <ignored/>
  </testcase> <!-- createContactTest -->
</testsuite> <!-- Test(failed)(failed) -->
